tomaka/hlua

lua52-sys/Cargo.toml
Lua versions share function names. It doesn't make sense to link to both lua5.2 and lua5.3 for example.
=> Change "links" from "lua52" to just "lua"

.travis.yml, README.md, hlua/examples/sound-api.rs, hlua/src/functions_write.rs, hlua/src/lib.rs, hlua/tests/functions_write.rs, hlua/tests/lua_tables.rs, hlua/tests/userdata.rs
Replaces `function` with `function0`, `function1`, `function2`, etc. depending on the number of parameters.
=> [Breaking change] Make hlua work on stable Rust

hlua/src/any.rs, hlua/tests/anyvalue.rs
I'm not entirely sure if this follows the guarantees for the LuaRead/Push traits. Please tell me if you notice anything.
This helps with some of the concerns of #66.
=> Add AnyLuaValue::LuaNil value

hlua/src/lib.rs, hlua/src/userdata.rs, lua52-sys/src/lib.rs
This includes improper_ctypes in lua52-sys, but implemented as #![allow(improper_ctypes)] on the module root. #[allow(improper_ctypes)] on the lua_State struct does not work. If this is merged, #72 should be closed.
It also removes the #[allow(raw_pointer_derive)] from hlua::LuaContext, since that is no longer needed and produces a warning on nightly.
The pr also provides fixes for rust-lang/rust#19925.
=> Fix various warnings from rustc

hlua/src/lua_tables.rs
Tables now have an index field, which keeps track of where they are in the lua stack, and the lua FFI functions are now offset relative to this index (when relevant.)
This is my first pull request on Github, and I know only as much about the Lua C API as I skimmed in the past hour or so, but I ran this through a small gauntlet of tests with Rust FFI functions accepting multiple user-data types that are pushed to and read from Lua as tables, and it seems to work. (My data types are all just vectors and matrices and such, though, so no nested tables. It may be worth giving a try with those if you have some on hand.)
Thanks!
=> Tables can be in any argument position for Rust functions

hlua/src/macros.rs, hlua/src/userdata.rs
This fixes a bug where functions could never be used with both User Data and standard types. The previous implementation was only able to handle User Data being the first parameter and even asserted that only 1 parameter was being used. The new implementation is dynamic over the index and works with any combination of User Data and standard types.
Fixes #75
=> Fix Functions not properly accepting User Data

README.md, hlua/src/any.rs, hlua/src/functions_read.rs, hlua/src/functions_write.rs, hlua/src/lib.rs, hlua/src/lua_tables.rs, hlua/src/macros.rs, hlua/src/rust_tables.rs, hlua/src/tuples.rs, hlua/src/userdata.rs, hlua/src/values.rs, hlua/tests/userdata.rs
Fix #77 
I had to add a lifetime parameter to `AsLua` and `AsMutLua`.
Unfortunately since the `Drop` impl of `PushGuard` requires that the template parameter of `PushGuard` implements `AsMutLua`, that means I would have to add a lifetime parameter to the `PushGuard` struct as well. In order to avoid that, I added a `raw_lua` member instead. Same for `LuaTableIterator`.
Eventually this PR could be "reverted" (ie. `raw_lua` removed) and lifetime parameters of `AsLua` and `AsMutLua` could become associated lifetimes.
=> Fix closures that can outlive environment

hlua/examples/basic.rs, hlua/src/functions_read.rs, hlua/src/lib.rs, hlua/src/values.rs
This PR greatly reduces the number of calls to `CString::new` and adds a basic example.
Running `cargo rustc --release --example basic -- --emit=asm` on this example now gives the following assembly (reorganized by me to follow jumps) which is very satisfying:
```asm
movq	$-2, 496(%rbp)
leaq	_ZN4hlua3Lua3new5alloc17h7ba710ca9ac163c0E(%rip), %rcx
xorl	%edx, %edx
callq	lua_newstate
movq	%rax, %rbx
testq	%rbx, %rbx
je	.LBB9_1
leaq	_ZN4hlua3Lua3new5panic17h36910d3e619d5a53E(%rip), %rdx
movq	%rbx, %rcx
callq	lua_atpanic
movq	%rbx, 440(%rbp)
movb	$1, 448(%rbp)
movl	$-1001000, %edx
movl	$2, %r8d
movq	%rbx, %rcx
callq	lua_rawgeti
leaq	str.c(%rip), %rdx
movl	$1, %r8d
movq	%rbx, %rcx
callq	lua_pushlstring
movl	$12, %edx
movq	%rbx, %rcx
callq	lua_pushinteger
movl	$-3, %edx
movq	%rbx, %rcx
callq …
```
=> Various optimizations

hlua/src/any.rs, hlua/src/functions_read.rs, hlua/src/functions_write.rs, hlua/src/lib.rs, hlua/src/lua_tables.rs, hlua/src/macros.rs, hlua/src/rust_tables.rs, hlua/src/tuples.rs, hlua/src/userdata.rs, hlua/src/values.rs, hlua/tests/userdata.rs
This PR allows pushing Lua code.
For example:
```
lua.set("foo", hlua::functions_read::LuaCode("return 5"));
```
You can then do:
```rust
let r = lua.execute_code::<i32>("foo()").unwrap();
assert_eq!(r, 5);
```
Similar to `LuaCode`, also adds `LuaCodeFromReader`.
This change required modifying the `Push` trait to return a `Result` instead, in order to handle syntax errors.
More code cleanups will need to be made later. Since the code was quite dirty already, I don't think it's a problem to add even more panicking corner cases.
=> Allows pushing Lua code

hlua/src/lib.rs, hlua/src/macros.rs, hlua/tests/anyvalue.rs, hlua/tests/userdata.rs
This is much less cumbersome in my opinion.
=> Hide all modules and reexports types in global scope

rust-hl-lua-modules/Cargo.toml, rust-hl-lua-modules/README.md
Adds a README with a warning, and tweaks the Cargo.toml in an attempt to fix https://github.com/rust-lang/cargo/issues/3441
=> Small changes to the rust-hl-lua-modules crate

hlua/src/userdata.rs
Fix #115 
The code is now much cleaner, and the type id is now stored directly in memory as described in #115 
Not everything has been reworked though.
Eventually `read_userdata` should be split between `read_userdata` and `read_mut_userdata` and implement for any `L` that implements `AsLua` or `AsMutLua`. Same for the `implement_lua_read!` macro that could finally become safe.
Unfortunately this is blocked on #118.
=> Userdata rework

hlua/src/functions_write.rs
An `Ok` will push the contained value, while an `Err` will push `nil`
and an error message.
Also changes the required trait for the error to `Display` instead of
`Debug`, which is more suitable for user-facing errors.
Closes #125
=> Make Result interoperable with Lua error handling

README.md, hlua/src/any.rs, hlua/src/lib.rs, hlua/src/rust_tables.rs
As it's impossible to `Eq` and `Hash` `f64`, I decided to split `AnyLuaValue`. I duplicated all variants instead of putting `AnyHashableLuaValue` inside of `AnyLuaValue` as that removes nesting, that would occur otherwise when handling `AnyHashableLuaValue`s produced by reading `HashMap`.
Close #9
=> Implement reading HashMap

hlua/src/any.rs, hlua/src/functions_write.rs, hlua/src/lib.rs, hlua/src/lua_functions.rs, hlua/src/rust_tables.rs, hlua/src/tuples.rs
This is most useful when poking at the Lua state directly.
The most important methods made public are `new` to create a new
`PushGuard`, and `forget` to not run this `PushGuard`'s destructor.
They're both unsafe because their misuse can easily cause the Lua
stack to be out of sync with Rust `PushGuard`s.
Also expose a `size` method to access the number of elements this
`PushGuard` is managing, and provide an internal-only safe version of
`forget` under the assumption that consumers within this crate know what
they're doing.
=> expose unsafe methods to create and forget PushGuards

lua52-sys/src/lib.rs
These are useful when adding things to the Lua registry. From the
documentation at http://pgl.yoyo.org/luai/i/luaL_ref:
> As long as you do not manually add integer keys into table t, luaL_ref
> ensures the uniqueness of the key it returns.
This can be done by hand with (say) an `AtomicIsize`, but it's just
easier to use these functions.
=> [lua52-sys] add ref/unref functions and helper constants

hlua/src/lib.rs, hlua/src/lua_functions.rs
* Make it implement `Error` when possible.
* Allow conversions from `LuaFunctionCallError<Void>` to `LuaError`.
=> add a few missing traits to LuaFunctionCallError

hlua/src/lua_functions.rs
This avoids a bunch of return statements and makes it clear that each
branch actually returns.
=> rewrite function return value handling to use a match statement

hlua/src/lib.rs, hlua/tests/ffi.rs
This is most useful when the caller wants to do low-level operations on
the state that aren't supported through the main API.
=> allow getting at the Lua state from a Lua object

hlua/src/values.rs
This was preventing binary strings from being passed correctly from Lua to Rust.
Fixes #156.
=> Parse strings entirely, without stopping at null bytes

hlua/src/any.rs, hlua/src/functions_write.rs, hlua/src/userdata.rs, hlua/tests/userdata.rs
the `Deref` and `DerefMut` impls previously always read from the index -1, which would be incorrect if the userdata were stored elsewhere. This adds an `index` field to `UserdataOnStack` which is filled in when it is created in `lua_read_at_position`, so that the value is always read from the correct position. This allows having userdata in function arguments aside from the first, for example.
=> Store index with UserdataOnStack so that correct value is read in Deref

lua52-sys/build.rs
=> Rename deprecated gcc::Config to gcc::Build

hlua/src/lib.rs
=> Remove usage of `mem::uninitialized()`

hlua/Cargo.toml
In the same way as #202 I would like to suggest a new release of the hlua crate. If necessary we can change this to 0.5.0.
=> Bump hlua to 0.4.2

hlua/src/userdata.rs
Fixed #219.
So I went on a bit of a journey in the #219 issue.
In conclusion, the address returned by `ffi::lua_newuserdata()` might be unaligned, which causes dereferencing `actual_typeid` to segfault due to a potential unaligned pointer. Changing it to allow for unaligned reads, results in all tests and all examples succeeding without segfaulting.
_I'm unsure if the subsequent `*data` can ever be unaligned. But I didn't run into it so far._
=> Fixed segfault when deref unaligned typeid

lua52-sys/Cargo.toml, lua52-sys/src/lib.rs
These function signatures are missing the return value.
Verified against `lualib.h`
=> Fix signatures of luaopen_* functions
