hlua/src/userdata.rs
Temporary fix so that hlua will compile with latest nightly
=> Allow mutable transmutes

hlua/src/lib.rs
Fixes #53.
All credit to @Kimundi for the updated signature to Lua.set().
=> Update to compile on 1.3.0 nightly

.travis.yml, hlua/src/functions_write.rs
=> Try fixing the compilation for rust stable

hlua/src/lib.rs, hlua/src/lua_tables.rs, hlua/tests/lua_tables.rs
Allows capturing the context by value instead of using a borrow, which is useful for embedding a long-living table in a struct.
=> By value captures

hlua/Cargo.toml
https://github.com/rust-lang/rust/pull/34198
=> Publish 0.1.9

hlua/src/lua_tables.rs
This should work for tables with positive stack indices.
=> Allow tables to be loaded from positive stack indices

README.md, hlua/Cargo.toml, lua52-sys/Cargo.toml
Also publish lua52-sys v0.1 since it doesn't make sense to use 0.0.x.
=> Publish 0.2.0 and update README

hlua/src/lib.rs, hlua/src/lua_tables.rs
=> Add LuaTable::registry to access the registry

hlua/src/lib.rs, hlua/src/lua_functions.rs
Fix #11 
I finally understood the issues with the borrow checker!
=> Allow passing arguments to LuaFunction::call

hlua/src/lib.rs, hlua/src/values.rs
Reads a Lua string without allocation.
=> Add StringInLua type

Cargo.toml, hlua/examples/repl.rs, lua52-sys/build.rs
=> Support `io.popen` on Linux

hlua/src/values.rs
* Some(T) pushes the T
* None pushes `nil`
Closes #124
=> Allow pushing Options

hlua/src/userdata.rs
Just FnOnce should be enough here.
=> Remove unnecessary FnMut bound

hlua/src/functions_write.rs, hlua/src/userdata.rs
This fixes #138 . However, see comments for newly added test.
=> Drop closure environment

hlua/src/any.rs, hlua/src/lib.rs, hlua/src/values.rs
=> Implement LuaPlainString for non-UTF-8

hlua/src/lib.rs, lua52-sys/src/lib.rs
=> Add methods to open individual libraries

hlua/src/lib.rs
=> Implement Error for LuaError

README.md, hlua/src/rust_tables.rs
=> Implement reading vectors of AnyLuaValue

hlua/Cargo.toml
=> Publish 0.4.0

hlua/Cargo.toml, lua52-sys/Cargo.toml
=> Fix publication

hlua/src/userdata.rs
While working with some userdata on a stack, I discovered that this would be really useful.
=> implement AsLua and AsMutLua for UserdataOnStack

hlua/src/functions_write.rs, hlua/src/lib.rs, hlua/src/lua_functions.rs, hlua/src/lua_tables.rs, hlua/src/userdata.rs
This proves to be pretty useful while debugging weird low-level Lua issues.
=> derive Debug for public types

hlua/src/any.rs
This is a breaking change, as it was previously the case that parsing a numeric string such as "-2" would return a `AnyLuaValue::LuaNumber`. It's up to the maintainer whether this is desired.
The code is ugly-branchy, since the two branches don't have the same type (the repeated parsing builds up `&`s on the `lua` variable.)
=> AnyLuaValue reads numeric strings as strings (fix #170)

hlua/src/any.rs
Matches the behaviour in #171 with `AnyHashableLuaValue`.
=> Read numeric strings into AnyHashableLuaValue as strings

hlua/src/any.rs
This, as far as I can tell, solves the issue of recursive `&mut` crashing the compiler in the same way that it was solved in `Push`.
Tests are a bit hairy but I can't think of a cleaner way to write them at the moment.
=> Implement reading arrays into AnyLuaValue and AnyHashableLuaValue

lua52-sys/Cargo.toml
As noted in https://github.com/tomaka/hlua/pull/199
=> Bump lua52-sys to 0.1.2
